module.exports = function(sequelize, DataTypes) {
	return sequelize.define('Toast', {
		sceneID:{
			type:DataTypes.UUID,
			notNull:true,
			primaryKey: true
		},
		completedAt:{
			type:DataTypes.DATE,
			notNull:true
		},
		requestedAt:{
			type:DataTypes.DATE,
			notNull:true
		},
		generatorName:{
			type:DataTypes.STRING(50),
			notNull:true
		},
		resourceType:{
			type:DataTypes.STRING(50),
			notNull:true
		},
		resourceURI:{
			type:DataTypes.STRING,
			notNull:true,
			isUrl:true
		},
		resultType:{
			type:DataTypes.STRING,
			notNull:true
		},
		resultURI:{
			type:DataTypes.STRING,
			notNull:true,
			isUrl:true,
		},
		tags:{
			type:DataTypes.STRING,
			allowNull:true
		},
		thumbnailURI:{
			type:DataTypes.STRING,
			isUrl:true,
			allowNull:true
		},
	},{
		timestamps:false
	});
};